@DeviceManagement.Api_HostAddress = http://localhost:5145
@UserId = 1
@AuthEmail = new.employee@darwin.local
@AuthPassword = Darwin123!
@AccessToken = paste-jwt-here

GET {{DeviceManagement.Api_HostAddress}}/
Accept: application/json

###

GET {{DeviceManagement.Api_HostAddress}}/api/users
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

GET {{DeviceManagement.Api_HostAddress}}/api/users/{{UserId}}
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{DeviceManagement.Api_HostAddress}}/api/users
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "name": "Andrei Marin",
  "role": "Support Engineer",
  "location": "Iasi"
}

###

PUT {{DeviceManagement.Api_HostAddress}}/api/users/{{UserId}}
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "name": "Alexandra Ionescu",
  "role": "Senior QA Engineer",
  "location": "Bucharest"
}

###

DELETE {{DeviceManagement.Api_HostAddress}}/api/users/{{UserId}}
Authorization: Bearer {{AccessToken}}

###

GET {{DeviceManagement.Api_HostAddress}}/api/devices
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

GET {{DeviceManagement.Api_HostAddress}}/api/devices/1
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{DeviceManagement.Api_HostAddress}}/api/devices
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "name": "Pixel 10",
  "manufacturer": "Google",
  "type": "phone",
  "operatingSystem": "Android",
  "osVersion": "16",
  "processor": "Tensor G5",
  "ramAmountGb": 12,
  "description": "Company-owned Android phone for field testing.",
  "location": "Bucharest",
  "assignedUserId": null
}

###

POST {{DeviceManagement.Api_HostAddress}}/api/devices/generate-description
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "name": "Pixel 10",
  "manufacturer": "Google",
  "type": "phone",
  "operatingSystem": "Android",
  "osVersion": "16",
  "processor": "Tensor G5",
  "ramAmountGb": 12
}

###

PUT {{DeviceManagement.Api_HostAddress}}/api/devices/1
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "name": "iPhone 15 Pro",
  "manufacturer": "Apple",
  "type": "phone",
  "operatingSystem": "iOS",
  "osVersion": "17.4",
  "processor": "A17 Pro",
  "ramAmountGb": 8,
  "description": "Updated sample payload for a protected device request.",
  "location": "Bucharest",
  "assignedUserId": null
}

###

DELETE {{DeviceManagement.Api_HostAddress}}/api/devices/1
Authorization: Bearer {{AccessToken}}

###

POST {{DeviceManagement.Api_HostAddress}}/api/devices/1/assign
Authorization: Bearer {{AccessToken}}

###

POST {{DeviceManagement.Api_HostAddress}}/api/devices/1/unassign
Authorization: Bearer {{AccessToken}}

###

POST {{DeviceManagement.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "{{AuthEmail}}",
  "password": "{{AuthPassword}}"
}

###

POST {{DeviceManagement.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "alexandra.ionescu@darwin.local",
  "password": "Darwin123!"
}

###
